export const ENV_WITH_AWS = `
DATABASE_URL="postgresql://admin:admin@localhost:5432/nest?schema=public"

PORT=3001

COGNITO_ACCESS_KEY_ID= # FILL THIS
COGNITO_SECRET_ACCESS_KEY= # FILL THIS
COGNITO_POOL_ID= # FILL THIS
COGNITO_CLIENT_ID= # FILL THIS
COGNITO_REGION= # FILL THIS
COGNITO_KEYS=[] # FILL THIS
COGNITO_DOMAIN= # FILL THIS
`
